In [1]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [6]:
arr2=np.array([[1,2,3],[2,3,4]])
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#linspace() Function in NumPy
"""
The linspace() function in NumPy is used to create an array of evenly 
spaced numbers over a specified range.

📌 Syntax
np.linspace(start, stop, num)
Parameters:
start → Starting value
stop → Ending value
num → Number of values you want
"""

arr8=np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [12]:
arr7=np.arange(4,18,2)

In [16]:
arr7

array([ 4,  6,  8, 10, 12, 14, 16])

In [15]:
arr9=arr7.copy()
arr9

array([ 4,  6,  8, 10, 12, 14, 16])

In [19]:
arr11=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
arr11.shape

(2, 2, 2)

In [21]:
arr11.ndim

3

In [22]:
arr1.ndim

1

In [23]:
arr3.ndim

2

In [24]:
arr2.shape

(2, 3)

In [25]:
arr1.size

4

In [26]:
arr11.size

8

In [27]:
arr5.size

16

In [28]:
arr7.itemsize

8

In [29]:
arr11.itemsize

8

In [30]:
arr1.itemsize


8

In [31]:
arr11.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [33]:
arr11.nbytes

64

In [35]:
arr11.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [40]:
lista=range(100)
arr12=np.arange(100)

In [41]:
import sys

In [42]:
print(sys.getsizeof(87)*len(lista))

2800


In [43]:
print(arr12.itemsize*arr12.size)

800


In [44]:
print("sid")

sid


In [45]:
arr15=np.arange(24).reshape(6,4)
arr15

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
arr15[2]

array([ 8,  9, 10, 11])

In [49]:
arr15[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [50]:
arr15[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [52]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr[0, 1])   # Row 0, Column 1
print(arr[0, 2])
print(arr[1,1])

2
3
5


In [54]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[0:1, 1:2])

[[2]]


In [55]:
arr15

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
for i in arr15:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [57]:
for i in np.nditer(arr15):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [58]:
for i in arr15.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [60]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [61]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [62]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [63]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [64]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [65]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [66]:
arr1.dot(arr2)

np.int64(154)

In [67]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [68]:
arr4.max()

np.int64(11)

In [69]:
arr4.min()

np.int64(6)

In [70]:
arr4.min(axis=0)

array([6, 7])

In [71]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [72]:
arr4.sum()

np.int64(51)

In [73]:
arr4.sum(axis=0)

array([24, 27])

In [74]:
arr4.mean()

np.float64(8.5)

In [75]:
arr4.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [76]:
arr4.std()

np.float64(1.707825127659933)

In [77]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [78]:
np.median(arr4)

np.float64(8.5)

In [79]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [80]:
"""
operation with array
| Operation Type  | Example       |
| --------------- | ------------- |
| Arithmetic      | `a + b`       |
| Scalar          | `a + 2`       |
| Comparison      | `a > 2`       |
| Aggregate       | `np.sum(a)`   |
| Math Functions  | `np.sqrt(a)`  |
| Matrix Multiply | `np.dot(a,b)` |
| Broadcasting    | `a + 2`       |

1. Arithmetic Operations
✅ Example:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division

👉 Output:

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
📌 2. Scalar Operations (Single Value)

👉 Apply operation to every element:

print(a + 2)
print(a * 3)

👉 Output:

[3 4 5]
[3 6 9]
📌 3. Comparison Operations
print(a > 2)
print(a == 2)

👉 Output:

[False False  True]
[False  True False]

✔ Returns True/False

📌 4. Aggregate Functions (Whole Array)
arr = np.array([1, 2, 3, 4])

print(np.sum(arr))   # Sum
print(np.mean(arr))  # Average
print(np.max(arr))   # Max
print(np.min(arr))   # Min

👉 Output:

10
2.5
4
1
📌 5. Mathematical Functions
arr = np.array([1, 4, 9])

print(np.sqrt(arr))   # Square root
print(np.exp(arr))    # Exponential
print(np.log(arr))    # Logarithm
📌 6. 2D Array Operations
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(a + b)

👉 Output:

[[ 6  8]
 [10 12]]
📌 7. Matrix Multiplication
print(np.dot(a, b))

👉 Output:

[[19 22]
 [43 50]]
📌 8. Broadcasting (Very Important 🔥)

👉 Different sizes but still works:
1. Arithmetic Operations
✅ Example:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division

👉 Output:

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
📌 2. Scalar Operations (Single Value)

👉 Apply operation to every element:

print(a + 2)
print(a * 3)

👉 Output:

[3 4 5]
[3 6 9]
📌 3. Comparison Operations
print(a > 2)
print(a == 2)

👉 Output:

[False False  True]
[False  True False]

✔ Returns True/False

📌 4. Aggregate Functions (Whole Array)
arr = np.array([1, 2, 3, 4])

print(np.sum(arr))   # Sum
print(np.mean(arr))  # Average
print(np.max(arr))   # Max
print(np.min(arr))   # Min

👉 Output:

10
2.5
4
1
📌 5. Mathematical Functions
arr = np.array([1, 4, 9])

print(np.sqrt(arr))   # Square root
print(np.exp(arr))    # Exponential
print(np.log(arr))    # Logarithm
📌 6. 2D Array Operations
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(a + b)

👉 Output:

[[ 6  8]
 [10 12]]
📌 7. Matrix Multiplication
print(np.dot(a, b))

👉 Output:

[[19 22]
 [43 50]]
📌 8. Broadcasting (Very Important 🔥)

👉 Different sizes but still works:
"""

a = np.array([1,2,3])
b = 2

print(a + b)





[3 4 5]


In [ ]:
# till the lesson 7