In [3]:
import numpy as np

a=np.arange(2,8).reshape(3,2)
b=np.arange(8,14).reshape(3,2)
print(np.add(a,b))

[[10 12]
 [14 16]
 [18 20]]


In [10]:
"""
Matrix Multiplication (Definition)

Matrix multiplication is a mathematical operation where two matrices are combined to produce a new matrix by multiplying rows of the first matrix with columns of the second matrix.

🧠 Simple Definition

Matrix multiplication is the process of taking the dot product of rows and columns from two matrices to form a new matrix.

📏 Condition (Important Rule)

If:

First matrix A has size (m × n)
Second matrix B has size (n × p)

👉 Then multiplication is possible, and the result will be a matrix of size (m × p).

🔢 How it works (Concept)

Each element of the result matrix is calculated as:

Take a row from matrix A
Take a column from matrix B
Multiply corresponding elements
Add them together
"""


import numpy as np
a=np.arange(2,6).reshape(2,2)
b=np.arange(8,12).reshape(2,2)
c=np.dot(a, b)
print(c)

[[46 51]
 [82 91]]


In [8]:
import numpy as np

# First matrix (2x2)
A = np.array([[1, 2],
              [3, 4]])

# Second matrix (2x2)
B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication
C = np.dot(A, B)

print(C)

[[19 22]
 [43 50]]


In [11]:
#Append, insert, delete

a=np.array([[20,40],[60,80]])
a

array([[20, 40],
       [60, 80]])

In [12]:
print(np.append(a,100))

[ 20  40  60  80 100]


In [13]:
print(np.insert(a,3,[70]))

[20 40 60 70 80]


In [23]:

a=np.array([[20,40],[60,80]])
print(np.insert(a,0, [1,2], axis=0))

[[ 1  2]
 [20 40]
 [60 80]]


In [25]:
print(np.delete(a,1,axis=0))

[[20 40]]


In [26]:
#sorting, searching, filter

print(np.sort(a))

[[20 40]
 [60 80]]


In [27]:
p=np.searchsorted(a,60)
print(p)

ValueError: object too deep for desired array